import { db } from "../firebase/firebase-config";
import { types } from '../types/types';



export const startNewUser = (uid, name) => {
    return async (dispatch) => {


        const newUser = {
            isCompany: true,
            name: `${name}`,
            fullName: "test OSR",
            birthday: "test",
            age: "test",
            sex: 1,
            phone1: "test",
            phone2: "test",
            rfc: "test",
            nationality: 2,
            state: 2,
            city: "test",
            postalCode: "test",
            country: 0,
            migrationStatus: 0,
            noStudiesNeeded: true,
            secundaria: true,
            bachillerato: true,
            licenciatura: true,
            licStatus: 2,
            licCareer: "",
            licIndustry: 2,
            maestria: true,
            maesDropdown: 2,
            doctorado: true,
            docDropdown: 2,
            urlVideo: "test",
            urlCurriculum: "test",
            experienceDescription: "test",
            plan: 2,
            position: "test",
            proofAdress: "test",
            socialReason: "test",
            hdaUrl: "test",
            actaConsUrl: "O.S.R rules",
            sitFiscalUrl: "test",
            domFiscUrl: "test",
            ineUrl: "test",
            selfRecognition: 0,
            selfEsteem: 0,
            procrastinationControl: 0,
            victimizationControl: 0,
            adaptability: 0,
            observation: 0,
            creativityInnovation: 0,
            entrepreneurshipInitiative: 0,
            improvisation: 0,
            problemSolving: 0,
            emotionalIntelligence: 0,
            rationalIntelligence: 0,
            focus: 0,
            collaboration: 0,
            negotiation: 0,
            selfConfidence: 0,
            frustrationTolerance: 0,
            assertiveCommunication: 0,
            conflictManagement: 0,
            resilience: 0,
            leadership: 0,
            reliability: 0,
            teamWork: 0,
            belongingSense: 0,
            empathy: 0,
        };

        await db.ref('users/' + uid).set(newUser);

        dispatch(userNew(
            newUser.isCompany,
            newUser.name,
            newUser.fullName,
            newUser.birthday,
            newUser.age,
            newUser.sex,
            newUser.phone1,
            newUser.phone2,
            newUser.rfc,
            newUser.nationality,
            newUser.state,
            newUser.city,
            newUser.postalCode,
            newUser.country,
            newUser.migrationStatus,
            newUser.noStudiesNeeded,
            newUser.secundaria,
            newUser.bachillerato,
            newUser.licenciatura,
            newUser.licStatus,
            newUser.licCareer,
            newUser.licIndustry,
            newUser.maestria,
            newUser.maesDropdown,
            newUser.doctorado,
            newUser.docDropdown,
            newUser.urlVideo,
            newUser.urlCurriculum,
            newUser.experienceDescription,
            newUser.plan,
            newUser.position,
            newUser.proofAdress,
            newUser.socialReason,
            newUser.hdaUrl,
            newUser.actaConsUrl,
            newUser.sitFiscalUrl,
            newUser.domFiscUrl,
            newUser.ineUrl,
            newUser.selfRecognition,
            newUser.selfEsteem,
            newUser.procrastinationControl,
            newUser.victimizationControl,
            newUser.adaptability,
            newUser.observation,
            newUser.creativityInnovation,
            newUser.entrepreneurshipInitiative,
            newUser.improvisation,
            newUser.problemSolving,
            newUser.emotionalIntelligence,
            newUser.rationalIntelligence,
            newUser.focus,
            newUser.collaboration,
            newUser.negotiation,
            newUser.selfConfidence,
            newUser.frustrationTolerance,
            newUser.assertiveCommunication,
            newUser.conflictManagement,
            newUser.resilience,
            newUser.leadership,
            newUser.reliability,
            newUser.teamWork,
            newUser.belongingSense,
            newUser.empathy,

        ));


    }
}


export const userNew = (
    isCompany,
    name,
    fullName,
    birthday,
    age,
    sex,
    phone1,
    phone2,
    rfc,
    nationality,
    state,
    city,
    postalCode,
    country,
    migrationStatus,
    noStudiesNeeded,
    secundaria,
    bachillerato,
    licenciatura,
    licStatus,
    licCareer,
    licIndustry,
    maestria,
    maesDropdown,
    doctorado,
    docDropdown,
    urlVideo,
    urlCurriculum,
    experienceDescription,
    plan,
    position,
    proofAdress,
    socialReason,
    hdaUrl,
    actaConsUrl,
    sitFiscalUrl,
    domFiscUrl,
    ineUrl,
    selfRecognition,
    selfEsteem,
    procrastinationControl,
    victimizationControl,
    adaptability,
    observation,
    creativityInnovation,
    entrepreneurshipInitiative,
    improvisation,
    problemSolving,
    emotionalIntelligence,
    rationalIntelligence,
    focus,
    collaboration,
    negotiation,
    selfConfidence,
    frustrationTolerance,
    assertiveCommunication,
    conflictManagement,
    resilience,
    leadership,
    reliability,
    teamWork,
    belongingSense,
    empathy,
) => ({
    type: types.userNew,
    payload: {
        isCompany,
        name,
        fullName,
        birthday,
        age,
        sex,
        phone1,
        phone2,
        rfc,
        nationality,
        state,
        city,
        postalCode,
        country,
        migrationStatus,
        noStudiesNeeded,
        secundaria,
        bachillerato,
        licenciatura,
        licStatus,
        licCareer,
        licIndustry,
        maestria,
        maesDropdown,
        doctorado,
        docDropdown,
        urlVideo,
        urlCurriculum,
        experienceDescription,
        plan,
        position,
        proofAdress,
        socialReason,
        hdaUrl,
        actaConsUrl,
        sitFiscalUrl,
        domFiscUrl,
        ineUrl,
        selfRecognition,
        selfEsteem,
        procrastinationControl,
        victimizationControl,
        adaptability,
        observation,
        creativityInnovation,
        entrepreneurshipInitiative,
        improvisation,
        problemSolving,
        emotionalIntelligence,
        rationalIntelligence,
        focus,
        collaboration,
        negotiation,
        selfConfidence,
        frustrationTolerance,
        assertiveCommunication,
        conflictManagement,
        resilience,
        leadership,
        reliability,
        teamWork,
        belongingSense,
        empathy,
    }
});

export const userCleaning = () => ({
    type: types.userCleaning
})